
sudo: required
language: java

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8



script:
  - mvn clean cobertura:cobertura -Dtest=0#021 -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/blueflood/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "IltZvEsAu9x0K25M5WKiIU/r4fCGiFHksOy/sutyJz7m7hu+3AaKnR5Vb+5RMyre0nD3RPhrHZDl3LL7Sb4NC+UsjgPYpypIXCRIuaJXCq0vjP2oNOvWKKnjrFwb3rLDIfetSNEuEZQsh1OGECCnInB5gXTfDeIHKmRo4RrHwbyWHUXoRS4McNyYeKpmZ0I3PoqQOTK8wBNwtpBp1zWgDSHUQvltMv3NJIGdsbOcZ04Dlbmyz6FRj30hxbuRJdFp/xK7D4sWJPZBiDAZZVt38glhnRCY3/uXB4GYa6eG0W9RY5XlwUNZm8liZmDtBvhykYhsqu2qBkBnA8Bnwo01W65q48tEgNtjUsIY4umGCzvG3xvgw+V/j4NVk/NT71ZFRmzQPoQ1zFijpjNifXpqa34QfVGbAPqJqy4P9IIs4f5F06pXJMQ+8sy9sL9irhBXvkJd3z+CUCZwxd/BsObhK/FyUUuiwWjbxzF1H55qL1XyRGxdgJSsaUt3Fe/gnqDX4P8iYhfD/knZdtxM0EmGoyV2fnLb/pYHGRS8bhkp1mQzQTLwEXGgQsfuGkGyrFkY06DKCkU5kGCQil2KEwmLtQQudMmD5lEsnxI7rPcQ78YGAlNoKxFO5Lws233fSr2y0/Ka6srZ1bKQQvPxkt6Z/fwSFqFUSkKAWRKAI/xdmfw="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
